const questions = [
  "CURRENT DC LOCATIONS",
  "CURRENT DR LOCATION",
  "TOTAL SERVER COUNT VIRTUALIZED TODAY",
  "CORES PER CPU CONFIGURED TODAY",
  "TOTAL USABLE STORAGE CONSUMED TODAY",
  "MONITORING TOOLS USED TODAY FOR SERVER/STORAGE/NETWORK/APPLICATIONS/DATABASES/SAP ETC",
  "RPO REQUIREMENTS",
  "RANSOMWARE PROTECTION REQUIRED",
  "AVG NUMBER OF VMS DEPLOYED PER MONTH BY ADMIN TEAM",
  "CURRENT SITE TO SITE CONNECTIVITY?",
  "LOVA/RVTOOLS REPORTS AVAILABLE?",
  "LICENSE CONSOLIDATION NEEDED?",
  "SERVER/STORAGE HARDWARE REFRESH REQUIRED IN NEXT 12 MONTHS?",
  "APPLICATIONS HOSTED IN AWS/AZURE/OTHER HYPERSCALER?",
  "WOULD YOU APPRECIATE AUTOMATED APPLICATION DISCOVERY AND VISIBILITY",  
  "ANY IT SERVICES / TECHNOLOGY SERVICES / BUSINESS SERVICES BEING PROVIDED TO YOUR CUSTOMERS",
  "LIST CURRENT BUSINESS CRITICAL APPLICATIONS THAT REQUIRE FULL STACK MONITORING",
  "LIST APPLICATIONS DEVELOPED IN-HOUSE",
  "APPLICATION ARCHITECTURE DIAGRAMS AVAILABLE?",
  "ANY 'COTS' APPS?",
  "ANY APPLICATIONS USING TOMCAT / IIS?",
  "IS WAF (WEB APPLICATION FIREWALL) REQUIRED FOR YOUR APPLICATIONS?",
  "LIST DATABASES IN USE? SUCH AS MYSQL/ORACLE/MSSQL/POSTGRES",
  "DO YOU REQUIRE SELF SERVICE APP ACCESS",
  "5RS INITIATIVE IN PLACE?",
  "DO YOU DEVELOP CUSTOMER SOLUTIONS?",
  "DO YOU HAVE HIGH PERFORMANCE REAL TIME APPLICATIONS?",
  "IS TRANSACTION INTEGRITY DESIRED FOR YOUR DISTRIBUTED APPLICATIONS?",
  "ARE IN HOUSE APPLICATION COMPONENTS DEVELOPED IN MULTIPLE LANGUAGES? IS CROSS LANGUAGE MESSAGING REQUIRED?",
  "DO YOU HAVE AUTOMATED LCM, BACKUPS, HA & MONITORING?",
  "DO YOU REQUIRE/DEVELOP ANALYTICAL MODELS FOR COMPLEX APPLICATIONS",
  "DO YOU NEED DEVELOPER SELF SERVICE ACCESS TO PLATFORM",
  "DO YOU NEED CURATED OPEN SOURCE IMAGES?",
  "DO YOU HAVE KUBERNETES CLUSTERS ACROSS SITES/CLOUDS?",
  "IS AUTOMATION OF KUBERNETES CLUSTERS REQUIRED?",
  "DO YOU WANT TO REDUCE NETWORK/IP ADDRESS PROVISIONING TIME?",
  "DO YOU HAVE IDS/IPS IN-USE?",
  "LIST ANY LOAD BALANCERS IN USE",
  "CURRENT PERIMETER FIREWALL(S)",
  "ANY ZTNA INITIATIVES/REQUIREMENTS?",
  "ANY SASE INITIATIVES",
  "KUBERNETES CLUSTER SECURITY / MICROSERVICES SECURITY",
  "ANY NETWORK DETECTION & RESPONSE (NDR) REQUIREMENTS",
  "ANY NETOWRK TRAFFIC ANALYSIS REQUIREMENTS",
  "SIMPLE AUTOMATION TASK (SAT)1 : ASSIGN AN IP ADDRESS FROM AN IP ADDRESS MANAGEMENT TOOL",
  "SAT2 : GENERATE A WORK ORDER TICKET",
  "SAT3 : UPDATE A CONFIGURATION MANAGEMENT DATABASE",
  "SAT4 : INITIATE A SYSTEM BACKUP",
  "SAT5 : AUTOMATE NEW EMPLOYEE ONBOARDING & OFF-BOARDING PROCESSES",
  "SAT6 : AUTOMATE ACTIVE DIRECTORY PROCESSES",
  "SAT7 : EXECUTE A CUSTOM QUERY ON A DATABASE",
  "SAT8 : GENERATE CRUD WORKFLOWS FOR A TABLE",
  "SAT9 : READ A CUSTOM QUERY FROM A DATABASE",
  "SAT10 : VM TEMPLATES TO BE DEFINED ONCE AND DEPLOYED AGNOSTIC TO ANY CLOUD (AWS/AZURE/ONPREMISE)",
  "SAT11 : INFRASTRUCTURE AUTOMATION",
  "SAT12 : SELF-SERVICE MULTI-CLOUD",
  "SIMPLE MONITORING TASK (SMT)1 : APACHE HADOOP MONITORING",
  "SMT2 : APACHE TOMCAT MONITORING",
  "SMT3 : ARISTA EOS MONITORING",
  "SMT4 : CISCO NETWORKING DEVICES MONITORING",
  "SMT5 : DELL EMC POWEREDGE MONITORING",
  "SMT6 : MICROSOFT AZURE SQL MONITORING",
  "SMT7 : MICROSOFT IIS SERVER MONITORING",
  "SMT8 : MICROSOFT SQL SERVER MONITORING",
  "SMT9 : MONGO DB MONITORING",
  "SMT10 : MYSQL MONITORING",
  "SMT11 : NAGIOS MONITORING",
  "SMT12 : NETAPP E-SERIES MONITORING",
  "SMT13 : NETAPP FAS/AFF MONITORING",
  "SMT14 : NETWORK DEVICES MONITORING",
  "SMT15 : NSX ADVANCED LOAD BALANCER MONITORING",
  "SMT16 : ORACLE DATABASE MONITORING",
  "SMT17 : ORACLE ENTERPRISE MANAGER MONITORING",
  "SMT18 : POSTGRESQL MONITORING",
  "SMT19 : RED HAT JBOSS EAP MONITORING",
  "SMT20 : SAP MONITORING",
  "SMT21 : SAP HANA MONITORING",
  "SMT22 : SOLARWINDS MONITORING",
  "SMT23 : STORAGE DEVICES MONITORING",
  "SMT24 : VSPHERE REPLICATION MONITORING",
  "SMT25 : OS AND APPLICATION MONITORING MONITORING",
  "NETWORK TASK (NT)1 : MONITOR/ANALYZE NETWORK PROBLEMS USING END-TO-END NETWORK BEHAVIOR",
  "NT2 : PERFORM ROOT-CAUSE ANALYSIS",
  "NT3 : PERFORM HEALTH ANALYSIS OF PHYSICAL AND VIRTUAL NETWORK DEVICES",
  "NT4 : BE CONTINUOUSLY AWARE OF THE TOP TALKING APPLICATIONS/VMS AND THEIR NETWORKING CONSTRUCTS",
  "NT5 : APP-CENTRIC NETWORK FLOW-BASED CONNECTIVITY TROUBLESHOOTING",
  "NT6 : PERFORM DETAILED NETWORK SECURITY & CAPACITY PLANNING",
  "NT7 : PERFORM AUTOMATED DETECTION OF LOOP IN NETWORK",
  "NT8 : PERFORM DAY 2 NETWORK OPERATIONS",
  "NT9 : UNDERSTAND TOPOLOGY & NETWORK PATH BETWEEN SOURCE & DESTINATION NETWORK DEVICES (ROUTERS/SWITCHES/FIREWALLS ETC)",
  "NT10 : DEPLOY NEW NETWORKS",
  "NT11 : MONITORING FOR DUPLICATE IP ADDRESSES",
  "NT12 : CREATION OF FWS, LBS, & ROUTING TOPOLOGY",
  "NT13 : UNDERSTAND CONNECTIVITY FOR VMs AND MICROSERVICES",
  "NT14 : MACS, APP ISOLATION, NETWORK RULES POLICIES E/W",
  "NT15 : UNDERSTAND ROUTING TOPOLOGY",
  "NT16 : MACS, APP ISOLATION, NETWORK RULES POLICIES N/S",
  "NT17 : VIP CREATION CONFIGURATION MANAGEMENT",
  "NT18 : NETWORK SOFTWARE PATCHES",
  "NT19 : NETWORK SOFTWARE FIRMWARE UPGRADES",
  "NT20 : NETWORK TROUBLESHOOTING",
  "NT21 : NETWORK MONITORING",
  "NT22 : AUDITING SECURITY POLICIES",
  "NT23 : REPORTING",
  "NT24 : ON DEMAND DMZs / ISOLATED SEGMENTS",
  "NT25 : NETWORK DIAGRAMS",
  "NT26 : OPTIMIZATIONS/ IMPROVEMENTS",
  "NT27 : UPDATING INVENTORY REPORTS",
  "NT28 : PREPARING MIGRATION STRATEGY",
  "NT29 : EVALUATING BUSINESS IMPACT",
  "NT30 : BUILDING TOPOLOGY MAPS",
  "NT31 : PREPARING NETWORK LOW LEVEL DESIGN",
  "NT32 : PREPARING MIGRATION PLAN",
  "NT33 : AUTOMATE IP ASSIGNMENT TO VMs",
  "NT34 : TRACKING AND VERIFYING MIGRATION CHANGES",
  "NT35 : FIREWALL MONITORING",
  "NT36 : FIREWALL RULES OPTIMIZATION",
  "NT37 : AUDIT AND COMPLIANCE",
  "NT38 : DEFINE NETWORK INTENT FOR DATACENTER",
  "NT39 : CONVERGED VISIBILITY AND PROBLEM DETECTION",
  "NT40 : LOG CHECKING MONITORING",
  "NT41 : UNDERSTANDING % N/S, E/W, AVERAGE, PEAK DATACENTER TRAFFIC",
  "NT42 : RISK ANALYSIS/ NEW TECHNOLOGY ADOPTION",
  "DO YOU REQUIRE CLOUD SPEND OPTIMIZATION & SECURITY",
  "DO YOU WANT TO AUTOMATE MANUAL OPERATIONAL TASKS WITH AUTOMATION",
  "DO YOU WANT TO INCREASE SHAREHOLDER VALUE",
  "DO YOU WANT TO IMPROVE ACCESS TO INFORMATION",
  "DO YOU WANT TO MITIGATE RISK DURING AUDITS",
  "DO YOU WANT TO MITIGATE RISK SUCH AS RANSOMWARE ATTACKS",
  "DO YOU WANT TO LOWER TCO",
  "DO YOU WANT TO MEET COMPLIANCE POLICIES",
  "DO YOU WANT TO ATTRACT/RETAIN STAFF",
  "DO YOU WANT TO VIRTUALIZE QUICKLY",
  "DO YOU WANT TO LEVERAGE EFFICIENCIES",
  "DO YOU WANT TO AVOID VENDOR LOCK-IN ACROSS CLOUDS", 
];


document.addEventListener('DOMContentLoaded', function() {
  const questionsDiv = document.getElementById('questions');
  questions.forEach((question, index) => {
    const label = document.createElement('label');
    label.textContent = `${index + 1}. ${question}`;
    const input = document.createElement('input');
    input.setAttribute('type', 'text');
    input.addEventListener('input', checkAllAnswers);
    questionsDiv.appendChild(label);
    questionsDiv.appendChild(input);
    questionsDiv.appendChild(document.createElement('br'));
  });
  
  showSubmit(); // Call this function to check if all questions are answered and show the submit button
});

function checkAllAnswers() {
  const inputs = document.querySelectorAll('#questions input');
  const submitDiv = document.getElementById('submitDiv');
  let allAnswered = true;

  inputs.forEach(input => {
    if (input.value.trim() === '') {
      allAnswered = false;
    }
  });

  if (allAnswered) {
    submitDiv.style.display = 'block';
  } else {
    submitDiv.style.display = 'none';
  }
}

function submitAnswers() {
  const inputs = document.querySelectorAll('#questions input');
  const tableBody = document.querySelector('#answers tbody');

  inputs.forEach((input, index) => {
    const question = questions[index];
    const answer = input.value.trim();

    if (answer !== '') {
      const newRow = tableBody.insertRow();
      const questionCell = newRow.insertCell();
      const answerCell = newRow.insertCell();

      questionCell.textContent = question;
      answerCell.textContent = answer;
    }
  });

  document.getElementById('submitDiv').style.display = 'none';
  document.getElementById('exportDiv').style.display = 'block';
  document.getElementById('answers').style.display = 'table';
}

function exportToCSV() {
  const table = document.getElementById('answers');
  const rows = table.querySelectorAll('tbody tr');
  let csv = 'Question,Answer\n';

  rows.forEach(row => {
    const question = row.cells[0].textContent;
    const answer = row.cells[1].textContent;
    csv += `"${question}","${answer}"\n`;
  });

  const blob = new Blob([csv], { type: 'text/csv' });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.setAttribute('href', url);
  a.setAttribute('download', 'questionnaire.csv');
  a.click();
  window.URL.revokeObjectURL(url);
}

function showSubmit() {
  document.getElementById('submitDiv').style.display = 'block';
}
